[package]
name = "rsed"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
console = "0.15.8"
indicatif = "0.17.8"
rand = "0.8.5"
regex = "1.11.1"
tokio = "1.41.0"
